version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: blindspotx
      POSTGRES_USER: blindspotx
      POSTGRES_PASSWORD: blindspotxpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    env_file: .env
    environment:
      DATABASE_URL: postgresql://blindspotx:blindspotxpass@db:5432/blindspotx
      SESSION_SECRET: supersecretkey
      # Azure environment variables will be loaded from .env file
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: gunicorn -b 0.0.0.0:5000 main:app
    restart: unless-stopped

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge 